PrestaShopCorp/psxmarketingwithgoogle

_dev/src/utils/Sentry.ts

We need to test it when the modification is on the CDN
https://docs.sentry.io/platforms/javascript/configuration/options/#allow-urls

Put CDN URL on allowUrls for only trigger module errors

---

_dev/src/components/product-feed/settings/shipping-settings/table-row-carrier.vue

Following a vue.js training, it appears having typescript in our component is possible with some changes, although the full compatibility would require Vue.js 3.

Retry introducing typescript in one Vue component

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-item.vue
_dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue

Also remove ID when it's the same at the name

Translate filter name if product condition

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/assets/scss/app.scss
_dev/src/assets/scss/base/_border.scss
_dev/src/assets/scss/base/_typography.scss
_dev/src/assets/scss/components/_sync-history.scss
_dev/src/components/product-feed-page/submitted-products/products-status-card.vue
_dev/src/components/product-feed-page/submitted-products/submitted-products.vue
_dev/src/components/product-feed-page/sync-history/sync-history.vue
_dev/src/components/product-feed-page/sync-history/sync-state.vue
_dev/src/components/product-feed-page/sync-overview.vue
_dev/src/components/product-feed/product-feed-card.vue
_dev/src/enums/product-feed/products-status-type.ts
_dev/src/enums/product-feed/sync-history.ts
_dev/stories/product-feed-card.stories.ts
_dev/stories/product-feed-overview.stories.ts

There is a big todo for the front-end dev.
```
// TODO
/**
* Create data structure for the sync history (vertical timeline)
* An ENUM has been written in _dev/src/enums/product-feed/sync-history.ts
* Use $t('productFeedPage.syncSummary.syncHistory.title.{$foo}') for the title
* (with foo being planned | started | failed | completed | next)
* Use $t('productFeedPage.syncSummary.syncHistory.subtitle.{$foo}', {date}) for the subtitle
* (with foo being willHappenOnDate | happenedOnDate | error)
* Icons and line colors are handled with css class:
* Icons might be: sync-history__item--icon-{foo}
* (with foo being check | schedule | cancel | change_circle)
* Line colors might be: sync-history__item--bg-{foo}, the line is to applied on the top
* (with foo being blue | red)
*/
```

Redesign of the product feed page

---

_dev/src/assets/scss/base/_color.scss
_dev/src/assets/scss/base/_common.scss
_dev/src/components/product-feed-page/submitted-products/products-status-card.vue
_dev/src/components/product-feed-page/sync-overview.vue

- Fix border color
- Fix link color
- Pruducts status cards are now clickable (link is TODO by the dev)

Fix product feed overview after design review

---

_dev/src/components/product-feed/settings/shipping-settings/shipping-settings.vue

Refactors shipping setting to have header cell hoverable

---

_dev/src/components/commons/badge-list-requirements.vue
_dev/src/components/commons/progress-ring.vue
_dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
_dev/src/components/product-feed-page/submitted-products/submitted-products.vue
_dev/src/components/product-feed/product-feed-card-next-sync-card.vue
_dev/src/components/product-feed/product-feed-card-report-card.vue
_dev/src/components/product-feed/product-feed-card-report-mapped-categories-card.vue
_dev/src/components/product-feed/product-feed-card-report-products-card.vue
_dev/src/components/product-feed/product-feed-card-report-products-sync-card.vue
_dev/src/components/product-feed/product-feed-card.vue
_dev/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
_dev/src/components/product-feed/settings/commons/actions-buttons.vue
_dev/src/components/product-feed/settings/summary/summary.vue
_dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-item.vue
_dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-recap.vue
_dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue

And also add all properties required for props in order to resolve all warnings from linter

FIX : display date problem in product feed settings summary 

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/commons/alert-update-module.vue
_dev/src/components/merchant-center-account/merchant-center-account-card.vue

1/ GMC after manually adding website address on claim
2/ error modules did not disappear after upgrade

Missing refresh message after user action

---

_dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
_dev/src/views/campaign-page.vue
_dev/stories/smart-shopping-campaign-creation.stories.ts

Also add a skeleton loader so we don't see all the empty inputs before loading the campaign to edit

Fix: load campaigns to find the one to edit

---

.github/workflows/build-release.yml
.github/workflows/cdn.yml

* Now delete the CDN version without wildcard

Improve CDN workflow

---

_dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue

Fix loading of campaign form after a refresh

---

_dev/src/components/product-feed/settings/summary/summary.vue
_dev/src/store/modules/product-feed/actions.ts

Add new sentence for multi synchro

---

_dev/src/assets/scss/layouts/_sticky-head.scss

Change the navbar size

---

_dev/src/components/merchant-center-account/website-requirements/step-store-info.vue

Check "no adult content" option by default

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/product-feed/product-feed-card.spec.ts

UI - Wording : button export feed

---

_dev/src/components/commons/banner-campaigns.vue
_dev/src/components/commons/popin-configured.vue

Tracking : add 2 new segment events

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/landing-page/landing-page-content.vue
_dev/src/components/landing-page/landing-page-footer.vue
_dev/src/components/landing-page/landing-page-header.vue
_dev/src/views/landing-page.vue

- Send 2 different segment events if click on footer or header button
- Remove links in footers of each block
- Change size of svg image ads-banner
- CSS on buttons start configuration (make them bigger)

Rework UI of the landing page 

---

_dev/src/components/product-feed/settings/shipping-settings/table-row-carrier.vue

Change icon duplicate
Add text for accessibility : "You can copy this carrier"

UXUI : shipping carriers updates

---

classes/Repository/AttributesRepository.php

This PR returns all the translated values of product features and attributes.
:warning: This breaks the attribute mapping step until it handles strings and arrays.

Attribute mapping values are now multilang

---

classes/Repository/AttributesRepository.php

Reverts PrestaShopCorp/psxmarketingwithgoogle#950

Revert "Attribute mapping values are now multilang"

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/merchant-center-account/website-requirements/step-requirements.vue
_dev/src/enums/merchant-center-account/website-requirements.ts

Reword new MCA funnel - requirements page

---

_dev/src/components/merchant-center-account/merchant-center-account-popin-website-requirements.vue

Decrease width of MCA requirements popin

---

_dev/src/components/google-account/google-account-popin-disconnect.vue
_dev/src/components/merchant-center-account/merchant-center-account-popin-disconnect.vue
_dev/src/store/modules/product-feed/actions.ts
_dev/src/utils/LocalStorage.ts

In order to remove all product feed settings saved

Delete localstorage when disconnecting Google ou Merchant Center accounts

---

_dev/src/components/commons/popin-configured.vue

CSS popin configured : title bigger

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/commons/select-country.vue
_dev/src/components/google-ads-account/google-ads-account-popin-new.spec.ts
_dev/src/components/google-ads-account/google-ads-account-popin-new.vue
_dev/stories/google-ads-account-popin-new.stories.ts

Display creation of Google Ads account in only one step

---

_dev/src/components/commons/banner-campaigns.vue
_dev/src/components/commons/not-configured-card.vue
_dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
_dev/src/components/smart-shopping-campaign/smart-shoppinh-campaign-table-list.spec.ts

Also Made some CSS quick fix (wrap text on button and blur header of the table + remove button create campaign because it's already on the banner)

Fix : empty states were not displayed on disconnect google ads

---

_dev/src/components/product-feed/product-feed-card.vue
_dev/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
_dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue

* Fixes an issue where attributes list is not shown on configuration page
* Fixes an issue caused by old data in localStorage

Fix some issues on product feed while testing beta.1

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/product-feed-page/sync-history/sync-history.vue

Add hour to next sync date

---

_dev/.storybook/mock/product-feed.js
_dev/src/assets/json/translations/de/ui.json
_dev/src/assets/json/translations/en/ui.json
_dev/src/assets/json/translations/es/ui.json
_dev/src/assets/json/translations/fr/ui.json
_dev/src/assets/json/translations/it/ui.json
_dev/src/assets/json/translations/nl/ui.json
_dev/src/assets/json/translations/pl/ui.json
_dev/src/assets/json/translations/pt/ui.json
_dev/src/assets/json/translations/ru/ui.json
_dev/src/components/product-feed/settings/attribute-mapping/attribute-field.spec.ts
_dev/src/store/modules/product-feed/state.ts
_dev/src/utils/AttributeMapping.ts

* Rename `shortDescription` as `description_short`
* Implement fallback for existing configurations

Make the attribute mapping values match the API

---

_dev/src/components/commons/select-country.vue
_dev/src/components/product-feed/settings/target-countries/target-countries.vue

Reverts PrestaShopCorp/psxmarketingwithgoogle#1012

Revert "Allow several countries to be set in product feed (will sync products for multiple countries)"

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/merchant-center-account/merchant-center-account-card.vue

Update wording when website verification fails

---

_dev/.storybook/mock/product-feed.js
_dev/src/assets/json/translations/en/ui.json
_dev/src/components/product-feed-page/sync-history/sync-history.vue
_dev/src/store/modules/product-feed/getters.ts
_dev/stories/product-feed-page.stories.ts

Also fix Storybook mock on attribute mapping

Fix add hour in status in export feed tab

---

_dev/.storybook/mock/campaigns-list.js
_dev/src/assets/scss/app.scss
_dev/src/assets/scss/components/_badge.scss
_dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list-row.vue
_dev/src/enums/reporting/CampaignStatus.ts

Add type of campaign next to its name

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue

Reverts PrestaShopCorp/psxmarketingwithgoogle#1059 because translation missing

Revert "Add tooltip to header product feed table prescan"

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/commons/banner-campaigns.vue

Banner campaign : change wording and cta

---

_dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-recap.vue
_dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue

Change campaign type to PMAX on post

---

composer.json

Will allow the module to be required via composer, making the dependencies checks easier
TODO:

Update composer.json for distribution via packagist

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/onboarding/section-title.vue
_dev/src/components/smart-shopping-campaigns/smart-shopping-campaign-card.vue
_dev/src/views/onboarding-page.vue

Update wording smart shopping campaign card

---

_dev/src/App.vue
_dev/src/assets/json/translations/en/ui.json
_dev/src/components/smart-shopping-campaigns/smart-shopping-campaign-card.vue
_dev/src/views/landing-page.vue

Also remove the "DID YOU KNOW" as requested

Update wording landing and configuration pages + banner

---

_dev/src/App.vue
_dev/src/assets/json/translations/en/ui.json
_dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table-row.vue

Change wording for banner

---

_dev/src/components/help/faq.vue

Display Youtube video on the Help tab

---

_dev/src/assets/json/translations/de/ui.json
_dev/src/assets/json/translations/en/ui.json
_dev/src/assets/json/translations/es/ui.json
_dev/src/assets/json/translations/fr/ui.json
_dev/src/assets/json/translations/it/ui.json
_dev/src/assets/json/translations/nl/ui.json
_dev/src/assets/json/translations/pl/ui.json
_dev/src/assets/json/translations/pt/ui.json
_dev/src/assets/json/translations/ru/ui.json
_dev/src/components/help/faq.vue

Reuse Help tab name in panel title

---

_dev/src/components/pmax/pmax-integration-modals/pmax-discover-modal.vue

Fix responsiveness of PMax modal

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/campaign-creation/campaign-creation.vue

Display feedback when campaign's end date is invalid

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/product-feed/product-feed-card.spec.ts
_dev/src/components/product-feed/product-feed-card.vue
_dev/src/components/product-feed/product-feed-settings.vue
_dev/src/components/product-feed/product-feed-stepper.vue
_dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
_dev/src/components/product-feed/settings/commons/actions-buttons.vue
_dev/src/components/product-feed/settings/shipping-settings/shipping-settings.vue
_dev/src/components/product-feed/settings/shipping-setup/shipping-setup.vue
_dev/src/components/product-feed/settings/summary/summary.vue
_dev/src/components/product-feed/settings/target-countries/target-countries.ts
_dev/src/enums/product-feed/product-feed-settings-pages.ts
_dev/src/enums/product-feed/product-feed-settings-steps.ts
_dev/src/enums/product-feed/shipping.ts
_dev/stories/product-feed-settings.stories.ts

Initial integration of new first step of shipping settings

---

_dev/.storybook/mock/product-feed.ts
_dev/src/assets/json/translations/en/ui.json
_dev/src/assets/scss/components/_productfeedreportcard.scss
_dev/src/components/product-feed/product-feed-card-report-card.vue
_dev/src/components/product-feed/product-feed-card.spec.ts
_dev/src/components/product-feed/product-feed-card.vue
_dev/src/components/product-feed/settings/summary/summary.spec.ts
_dev/src/components/product-feed/settings/summary/summary.vue
_dev/src/components/product-feed/summary/product-feed-summary-cards.vue
_dev/stories/product-feed-settings.stories.ts
_dev/stories/product-feed-summary-cards.stories.ts

Integrate summary with new shipping settings

---

_dev/.storybook/mock/state-app.ts
_dev/src/components/campaign-creation/campaign-creation.spec.ts
_dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.spec.ts
_dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue

Add unit tests on Target Countries component

---

_dev/src/components/product-feed/product-feed-settings.vue

Fixing error with this ticket https://forge.prestashop.com/secure/RapidBoard.jspa?rapidView=274&projectKey=EMKTG&view=detail&selectedIssue=EMKTG-1995

Save the current position of stepper inside funnel

---

_dev/src/components/product-feed/product-feed-settings.vue

Reverts PrestaShopCorp/psxmarketingwithgoogle#1252

Revert "Save the current position of stepper inside funnel"

---

_dev/src/App.vue
_dev/src/assets/scss/layouts/_sticky-head.scss

Fix z index of tabs & allow override of their style

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/assets/scss/abstracts/_variables.scss
_dev/src/assets/scss/base/_color.scss
_dev/src/assets/scss/base/_common.scss
_dev/src/assets/scss/base/_typography.scss
_dev/src/components/commons/alert-module-disabled.vue
_dev/src/components/commons/alert-update-module.vue
_dev/src/components/onboarding/section-title.spec.ts
_dev/src/components/onboarding/section-title.vue
_dev/src/views/onboarding-page.vue

Changing onboarding view for 2panels

---

_dev/src/assets/scss/components/_onboardingcard.scss
_dev/src/components/google-account/google-account-card.spec.ts
_dev/src/components/google-account/google-account-card.vue
_dev/src/views/onboarding-page.vue

Merge all cards of the same step

---

_dev/src/assets/json/translations/en/ui.json

Update title of campaigns page banner

---

_dev/.storybook/preview.js
_dev/package-lock.json
_dev/package.json
_dev/src/App.vue
_dev/src/lib/segment/index.ts
_dev/src/main.ts
_dev/src/views/onboarding-page.vue

**Pros:**
* Fixes the conflict between all the existing segment instances at the same time
* Use latest version of analytics.js (v2)
**Cons:**
* Use v4 of accounts vue -> Different styles are visible on a same page
* ~Debug mode does not work at the moment~
* ~If the CDN fails, we have no fallback~

Switch on analytics-next to avoid conflicts on SMB

---

_dev/src/assets/scss/components/_onboardingcard.scss
_dev/src/assets/scss/vendors/_bootstrap-vue.scss

Fix loading state from this
to this
And bring back skeleton for other loading states

Fix display of loading states

---

_dev/src/assets/json/translations/de/ui.json
_dev/src/assets/json/translations/en/ui.json
_dev/src/assets/json/translations/es/ui.json
_dev/src/assets/json/translations/fr/ui.json
_dev/src/assets/json/translations/it/ui.json
_dev/src/assets/json/translations/nl/ui.json
_dev/src/assets/json/translations/pl/ui.json
_dev/src/assets/json/translations/pt/ui.json
_dev/src/assets/json/translations/ru/ui.json
_dev/src/assets/scss/components/_stepper.scss
_dev/src/components/google-account/google-account-card.vue
_dev/src/components/google-ads-account/google-ads-account-card.vue
_dev/src/components/product-feed/summary/product-feed-summary-cards.vue
_dev/src/views/onboarding-page.vue

* Fix width of vertical stepper
* Improve stickiness limits
* Reduce space between product feed steps and edit button
* Remove space after google account email
* Update button when Google Ads account card is disabled

Changes from feedback of beta.8

---

_dev/src/components/commons/select-country.spec.ts
_dev/src/components/commons/select-country.vue
_dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
_dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
_dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-rate.vue
_dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue

Reverts PrestaShopCorp/psxmarketingwithgoogle#1023 that reverts https://github.com/PrestaShopCorp/psxmarketingwithgoogle/pull/1012

Allow several countries to be set in product feed (will sync products for multiple countries)

---

_dev/src/assets/scss/abstracts/_variables.scss
_dev/src/assets/scss/base/_typography.scss

- Fix positions of step numbers on configuration page
- Fix border of inputs with focus state

  Changes from feedback of beta.10

---

_dev/src/store/modules/accounts/actions.ts

https://forge.prestashop.com/browse/EMKTG-1770
Dispatch `SAVE_WEBSITE_VERIFICATION_META` from `REQUEST_WEBSITE_CLAIMING_STATUS`

Automatically dispatch claim verification meta if claimed or no not verified

---

_dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue

https://forge.prestashop.com/browse/EMKTG-1845

EMKTG-1845: Remove cache storing on step back attribute mapping

---

_dev/src/components/campaigns/campaign-card.vue

display popin remarketing tag if tracking tag not toggle on the onboarding page

EMKTG-1892: Fix onboarding popin tracking tag

---

_dev/src/assets/scss/abstracts/_variables.scss
_dev/src/assets/scss/base/_common.scss
_dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue

Resolve issue from review of estimate carrier UX

---

_dev/.storybook/mock/product-feed.ts
_dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.spec.ts
_dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
_dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
_dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-rate.vue
_dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.spec.ts
_dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
_dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.spec.ts
_dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue
_dev/src/enums/product-feed/attribute-mapping-categories.ts
_dev/src/providers/shipping-settings-provider.ts
_dev/src/store/modules/product-feed/actions.ts
_dev/src/store/modules/product-feed/getters.ts
_dev/src/store/modules/product-feed/mutations.ts
_dev/src/store/modules/product-feed/state.ts

Remaining question: Should we reset the selected rate on country update?

Reset carrier forms on country updates

---

_dev/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
_dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue

fix(AttributeMapping): store mapping in local variable

---

_dev/src/assets/json/prestashopUrl.json
_dev/src/components/help/faq.vue

fix(FAQ): contact button open the contact form of prestashop

---

_dev/src/components/campaign/reporting/campaigns-performance/campaigns-performance-table-row.vue

Update style of badges in reports tab

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/campaign-creation/campaign-creation.spec.ts
_dev/src/components/campaign-creation/campaign-creation.vue

Display a specific message when the campaign name is too long

---

_dev/.storybook/preview.js
_dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.spec.ts
_dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
_dev/src/store/modules/product-feed/actions.ts
_dev/stories/product-feed-settings.stories.ts

:notebook: From now, previously saved data will be reloaded each time the selected categories are updated.

Fix dynamic display of attributes list to map

---

_dev/package-lock.json
_dev/package.json
_dev/src/utils/Sentry.ts

For more information: https://sentry.io/for/session-replay/

Enable Replays on Sentry

---

controllers/admin/AdminPsxMktgWithGoogleModuleController.php

From @tberger-prestashop's report

Load CSC from CloudSync module when installed version is at least 1.9.0

---

_dev/src/components/campaign-creation/campaign-creation.vue
_dev/src/utils/Filters.ts

JIRA: EMKTG-2231
JIRA: EMKTG-2232

feat(Campaign): Use currency symbol from GoogleAds currency

---

_dev/src/assets/json/translations/en/ui.json
_dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
_dev/stories/product-feed-pre-scan-table-status.stories.ts

Add new message when targetCountries and shop language not matched

---

_dev/apps/ui/src/assets/json/translations/en/ui.json
_dev/apps/ui/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
_dev/apps/ui/src/components/product-feed-page/submitted-products/submitted-products.vue
_dev/apps/ui/stories/product-feed-page.stories.ts
_dev/apps/ui/stories/product-feed-pre-scan-table-status.stories.ts

Add message in productFeedPage summary for prescan error lang

---

_dev/packages/mktg-with-google-common/api/HttpClientError.ts

Change constructor call

---

classes/Handler/RemarketingHookHandler.php

Similar to https://github.com/PrestaShopCorp/ps_facebook/pull/407

Fix paths to template paths

---

_dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details-row.vue
_dev/apps/ui/stories/product-feed-table-status-details.stories.ts

Fix alignment of data in product feed table when all destination do not have the same status

---

.github/workflows/publish.yml

This PR should fix the upload of sourcemaps on Sentry to ease the debugging.

Fix use of variable in workflow

---

_dev/apps/ui/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
_dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details.vue
_dev/apps/ui/tests/init.ts
_dev/packages/mktg-with-google-common/translations/en/ui.json

The timeline part is under conception, wording will be added later.

[Product feed] Add wording for new product feed dashboard

---

_dev/apps/ui/src/components/merchant-center-account/merchant-center-account-popin-website-requirements.vue
_dev/apps/ui/src/components/product-feed/settings/commons/settings-footer.vue

Display info icon in light grey

---

_dev/apps/ui/src/assets/scss/abstracts/_variables.scss
_dev/apps/ui/src/assets/scss/base/_common.scss
_dev/apps/ui/src/assets/scss/components/_product-category-checkbox.scss
_dev/apps/ui/src/assets/scss/components/_shipping_setup.scss
_dev/apps/ui/src/assets/scss/layouts/_form.scss
_dev/apps/ui/src/assets/scss/layouts/_table.scss
_dev/apps/ui/stories/base-alerts.stories.ts

Update background colors of alerts

---

_dev/apps/ui/src/assets/scss/components/_badge.scss
_dev/apps/ui/src/assets/scss/components/_sync-history.scss
_dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
_dev/apps/ui/src/components/product-feed-page/dashboard/status-card.vue

Update style from design check

---

_dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details.vue

- Fix style of breadcrumb (add more height)
- Fix link of the first element of the breadcrumb ("Product feed" should redirect to the product feed tab)

Improve header of product status details in product feed

---

_dev/apps/ui/.storybook/mock/product-feed.ts
_dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-page.vue
_dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-row.vue
_dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details.vue
_dev/packages/mktg-with-google-common/translations/en/ui.json

Allow singular form of 'View products'

---

_dev/apps/ui/.storybook/mock/product-feed.ts
_dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
_dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration.ts
_dev/apps/ui/src/components/product-feed-page/dashboard/panel/submitted-products.vue
_dev/apps/ui/src/components/product-feed-page/dashboard/status-card.vue
_dev/apps/ui/src/components/product-feed-page/dashboard/sync-overview.vue
_dev/apps/ui/src/components/product-feed-page/non-compliant-products-details-page/non-compliant-products-details-row.vue

* New properties:
* ggl_gmc_account_is_suspended
* ggl_sync_is_multi_target_countries
* ggl_sync_is_multi_languages
* ggl_sync_is_multi_currencies
* ggl_user_has_compliant_products
* ggl_user_has_non_compliant_products
* ggl_user_has_approved_products_on_gmc
* ggl_user_has_disapproved_products_on_gmc
* New actions:
* Click on languages
* Click on Target countries
* Click on status card
* Click on link to edit product

Fix source of currencies list + add events about product feed status

---

_dev/apps/ui/src/components/product-feed-page/dashboard/panel/verified-products.vue

Make non-compliant card clickable even with value zero

---

_dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.spec.ts
_dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
_dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-row.vue
_dev/apps/ui/stories/product-feed-page/dashboard/product-feed-page-components-configuration.stories.ts
_dev/packages/mktg-with-google-common/translations/en/ui.json

Display errors about ineligible langs or currencies

---

_dev/apps/ui/src/main.ts

Prevent rebranding on PrestaShop Edition to alter our interface

---

_dev/apps/ui/src/components/merchant-center-account/merchant-center-account-card.vue
_dev/apps/ui/src/views/debug.vue

Add a button in the debug tab to force the creation of GMC accounts

---

_dev/apps/ui/src/components/campaign-creation/campaign-creation-filter-popin/campaign-creation-popin-recap.vue
_dev/apps/ui/src/components/campaign-creation/campaign-creation.vue

Some refacto has been done at the same time to remove duplicated content.

Fix status of campaign during edition

---

_dev/apps/ui/.storybook/mock/campaigns-list.ts
_dev/apps/ui/.storybook/mock/campaigns.ts
_dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
_dev/apps/ui/src/components/campaign/campaign-table-list.spec.ts
_dev/apps/ui/src/components/campaign/campaign-table-list.vue
_dev/apps/ui/src/router/index.ts
_dev/apps/ui/src/store/modules/campaigns/actions.ts
_dev/apps/ui/src/store/modules/campaigns/getters.ts
_dev/apps/ui/src/store/modules/campaigns/mutations.ts
_dev/apps/ui/src/store/modules/campaigns/state.ts
_dev/apps/ui/src/views/onboarding-page.vue
_dev/apps/ui/stories/banners-ads-overviews.stories.ts
_dev/apps/ui/stories/smart-shopping-campaign-creation.stories.ts
_dev/apps/ui/stories/smart-shopping-campaign-table-list.stories.ts

Need to wait https://github.com/PrestaShopCorp/services/pull/2893 before merging

Remove SSC occurrences

---

_dev/apps/ui/src/components/campaign/reporting/key-metrics/key-metrics-chart-wrapper.vue

Improve display of several y axis

---

_dev/packages/mktg-with-google-common/translations/en/ui.json

Update wording of campaigns tab + breadcrumbs

---

_dev/apps/ui/src/components/campaign/reporting/key-metrics/key-metrics-chart-wrapper.spec.ts
_dev/apps/ui/src/components/campaign/reporting/key-metrics/key-metrics-chart-wrapper.vue
_dev/apps/ui/src/utils/ChartTooltip.ts
_dev/apps/ui/stories/campaigns-page/dashboard/campaign-page-components-daily-results-chart.stories.ts
_dev/apps/ui/stories/campaigns-page/dashboard/campaign-page-components-key-metrics.stories.ts

Implement our design on graph tooltips

---

_dev/apps/ui/src/components/campaign/reporting/key-metrics/key-metrics-chart-wrapper.spec.ts
_dev/apps/ui/src/components/campaign/reporting/key-metrics/key-metrics-chart-wrapper.vue
_dev/apps/ui/src/utils/ChartTooltip.ts

Display points on graph on hover

---

_dev/apps/ui/src/components/merchant-center-account/merchant-center-account-card.vue
_dev/apps/ui/stories/merchant-center-account-card.stories.ts

Add missing stories about GMC card

---

_dev/apps/ui/src/components/campaign/campaign-table-list-row.vue
_dev/apps/ui/src/components/campaign/campaign-table-list.vue
_dev/apps/ui/src/components/campaign/reporting/key-metrics/key-metrics-block.vue
_dev/apps/ui/src/components/campaign/reporting/key-metrics/key-metrics-period-selector.vue

New events:
* `[GGL] Campaigns list - Click on edit button`
* `[GGL] Campaigns list - Update status of campaign`
* `[GGL] Campaigns list - Update sorting`
* `[GGL] Reporting - Toggle KPI highlighted`
* `[GGL] Reporting - Change period`

Add segment on new campaign page

---

_dev/apps/ui/src/assets/scss/abstracts/_variables.scss
_dev/apps/ui/src/assets/scss/base/_border.scss
_dev/apps/ui/src/assets/scss/components/_breadcrumb.scss
_dev/apps/ui/src/assets/scss/layouts/_form.scss
_dev/apps/ui/src/components/campaign/campaign-table-list.vue
_dev/apps/ui/src/components/campaign/reporting/key-metrics/key-metrics-block.vue
_dev/apps/ui/src/components/product-feed-page/dashboard/sync-overview.vue
_dev/apps/ui/src/views/onboarding-page.vue
_dev/apps/ui/stories/breadcrumb.stories.ts

- Remove more border radius properties
- Update color of text in card headers
- Update width of columns in onboarding page to have something like (col-5 / col-7)

Update global style of app

---

_dev/apps/ui/src/main.ts

- https://segment.com/docs/connections/spec/best-practices-identify/
- https://segment.com/docs/connections/spec/alias/

Link anonymous ID with User ID when possible

---

_dev/apps/ui/src/components/product-feed-page/dashboard/status-card.spec.ts
_dev/apps/ui/src/components/product-feed-page/dashboard/status-card.vue

Display status cards as aligned to the left

---

_dev/apps/ui/src/assets/scss/components/_nav.scss

Backported from PS Social https://github.com/PrestaShopCorp/ps_facebook/pull/478/commits/00da4dd4b24f1bd3229efedd511b76eed395ffbf

Update style tabs

---

_dev/apps/ui/src/components/enhanced-conversions/alert-ec-ready.vue

Make enhanced conversion enabler alert dismissible

---

_dev/apps/ui/src/components/campaign-creation/campaign-creation.spec.ts
_dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
_dev/packages/mktg-with-google-common/translations/en/ui.json

Enforce check on minimum budget during campaign edition

---

_dev/apps/ui/.storybook/mock/campaigns-list.ts
_dev/apps/ui/.storybook/mock/campaigns.ts
_dev/apps/ui/src/assets/scss/abstracts/_variables.scss
_dev/apps/ui/src/assets/scss/app.scss
_dev/apps/ui/src/assets/scss/components/_alert-mini.scss
_dev/apps/ui/src/components/campaign/alert-low-budget.vue
_dev/apps/ui/src/components/campaign/campaign-table-list-row.spec.ts
_dev/apps/ui/src/components/campaign/campaign-table-list-row.vue
_dev/apps/ui/src/store/modules/campaigns/actions.ts
_dev/apps/ui/src/store/modules/campaigns/state.ts
_dev/apps/ui/stories/campaigns-page/dashboard/campaign-page-components-list.stories.ts
_dev/apps/ui/stories/smart-shopping-campaign-creation.stories.ts
_dev/packages/mktg-with-google-common/translations/en/ui.json

Display an alert on campaigns list when campaign has a low budget

---

_dev/apps/ui/src/assets/scss/components/_alert-mini.scss

Fix break when page width is limited

---

_dev/apps/ui/src/assets/scss/components/_badge.scss
_dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
_dev/packages/mktg-with-google-common/translations/en/ui.json

Add spaces around badges

---

_dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue

Diff to read with whitespace changes ignored
https://github.com/PrestaShopCorp/psxmarketingwithgoogle/assets/6768917/b1863a61-9e67-4f51-a5ae-beb8d8b9bfab

Improve responsiveness of product feed settings

---

_dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
_dev/apps/ui/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.spec.ts
_dev/apps/ui/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
_dev/apps/ui/src/components/product-feed/settings/delivery-time-and-rates/import-method/table-row-carrier.vue
_dev/apps/ui/src/store/modules/product-feed/actions.ts

* Fix an issue preventing the list of carriers to be properly refreshed
* Fix an issue on the carriers details duplication

Improve reactiveness on carriers form

---

_dev/apps/ui/src/store/modules/product-feed/actions.ts

Related to https://github.com/PrestaShopCorp/psxmarketingwithgoogle/pull/1643
I'm very sorry Thomas for this 😓

Dumb issue with endpoint name

---

_dev/apps/ui/src/assets/scss/app.scss
_dev/apps/ui/src/assets/scss/components/_google-issues.scss
_dev/apps/ui/src/components/merchant-center-account/merchant-center-account-alert-suspended.vue
_dev/apps/ui/src/components/product-feed-page/disapproved-products-page/popin-product-issues.vue
_dev/apps/ui/src/components/render-issues/account-issues.types.ts
_dev/apps/ui/src/components/render-issues/collapsing-issues.spec.ts
_dev/apps/ui/src/components/render-issues/collapsing-issues.vue
_dev/apps/ui/src/components/render-issues/product-issues.types.ts
_dev/apps/ui/src/components/render-issues/types.ts
_dev/apps/ui/src/store/modules/accounts/state.ts
_dev/apps/ui/stories/product-feed-page/disapproved-products-page/popin-product-issues.stories.ts
_dev/packages/mktg-with-google-common/translations/en/ui.json

Introduce product issues + fix display of tooltips

---

_dev/apps/ui/src/components/commons/card-collapse-loading.vue
_dev/apps/ui/src/components/product-feed-page/disapproved-products-page/popin-product-issues.vue

Add a loading state while loading product issues

---

_dev/apps/ui/src/store/modules/product-feed/actions.ts

Reverts PrestaShopCorp/psxmarketingwithgoogle#1662, the original PR should have targeted 1.65.x

Revert "Set a limit when loading disapproved products"

---

_dev/apps/ui/src/components/product-feed-page/disapproved-products-page/disapproved-products-page.vue

This PR fixes an issue where the load of a next page was always attempted

Update management of page load on scroll

---

_dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
_dev/apps/ui/src/components/merchant-center-account/website-requirements/step-requirements.vue
_dev/apps/ui/src/components/merchant-center-account/website-requirements/step-store-info.vue
_dev/apps/ui/src/components/product-feed-page/dashboard/panel/submitted-products.vue
_dev/apps/ui/src/components/product-feed-page/dashboard/panel/verified-products.vue
_dev/apps/ui/src/components/product-feed-page/dashboard/status-card.vue
_dev/apps/ui/src/components/product-feed/product-feed-card-report-card.vue
_dev/apps/ui/src/components/product-feed/product-feed-card-report-products-card.vue
_dev/apps/ui/src/components/product-feed/product-feed-card-report-products-sync-card.vue
_dev/apps/ui/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
_dev/apps/ui/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
_dev/apps/ui/src/components/product-feed/settings/commons/settings-footer.vue
_dev/apps/ui/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
_dev/apps/ui/src/store/modules/product-feed/actions.ts

Backported from https://github.com/PrestaShopCorp/ps_facebook/pull/538

Add class material icon before rounded one

---

_dev/apps/ui/src/store/modules/product-feed/actions.ts

fix: rollback changes as useless
The necessary changes to fix the bug were done on the back.
The fix here wasn't one and it created a regression.

EMKTG-3254/fix/rollback useless changes

---

_dev/apps/ui/src/assets/scss/components/_button.scss
_dev/apps/ui/src/components/commons/alert-cmp.vue
_dev/apps/ui/src/views/onboarding-page.vue
_dev/packages/mktg-with-google-common/translations/en/ui.json

US => [EMKTG-3237](https://forge.prestashop.com/browse/EMKTG-3237)

Cmp message

---

_dev/apps/ui/src/components/commons/alert-cmp.vue
_dev/apps/ui/src/components/product-feed/product-feed-settings.vue
_dev/apps/ui/src/components/product-feed/product-feed-stepper.vue
_dev/apps/ui/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
_dev/apps/ui/src/components/product-feed/settings/sync-schedule/sync-schedule.vue
_dev/apps/ui/src/enums/product-feed/product-feed-settings-pages.ts
_dev/apps/ui/src/enums/product-feed/product-feed-settings-steps.ts
_dev/apps/ui/src/store/modules/accounts/actions.ts
_dev/apps/ui/src/store/modules/product-feed/actions.ts

- Remove production selection step
- Fix some translations

Fix: cmp message

---

_dev/apps/ui/src/components/product-feed-page/dashboard/panel/verified-products.vue
_dev/packages/mktg-with-google-common/translations/en/ui.json

Front part of this us => [EMKTG-3311](https://forge.prestashop.com/browse/EMKTG-3311)

fix: update typo to match with product filter

---

_dev/apps/ui/src/components/product-feed/settings/product-selection/line-filter.vue
_dev/apps/ui/src/components/product-feed/settings/product-selection/product-selection.vue
classes/ProductFilter/FilterApplication/AttributeQueryBuilder/CategoryQueryBuilder.php

Related tickets =>
- [EMKTG-3400](https://forge.prestashop.com/browse/EMKTG-3400)
- [EMKTG-3403](https://forge.prestashop.com/browse/EMKTG-3403)
- [EMKTG-3399](https://forge.prestashop.com/browse/EMKTG-3399)

Fix : feedback QA

---

_dev/apps/ui/src/assets/scss/pages/_product-selection.scss
_dev/apps/ui/src/components/product-feed/product-feed-popin-cancel.vue
_dev/apps/ui/src/components/product-feed/settings/product-selection/line-filter.vue
_dev/apps/ui/src/components/product-feed/settings/product-selection/product-selection.vue
_dev/apps/ui/src/views/tunnel-product-feed.vue

Related tickets =>
- [EMKTG-3407](https://forge.prestashop.com/browse/EMKTG-3407)
- [EMKTG-3408](https://forge.prestashop.com/browse/EMKTG-3408)

Fix: QA feedback

---

_dev/apps/ui/src/components/product-feed/product-feed-settings.vue
_dev/apps/ui/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
_dev/apps/ui/src/components/product-feed/settings/product-selection/product-selection.vue
_dev/apps/ui/src/components/product-feed/settings/shipping-setup/shipping-setup.vue
_dev/apps/ui/src/components/product-feed/settings/summary/summary.vue
_dev/apps/ui/src/views/onboarding-page.vue
_dev/apps/ui/src/views/tunnel-product-feed.vue

Related tickets =>
- [EMKTG-3407](https://forge.prestashop.com/browse/EMKTG-3407)
- [EMKTG-3410](https://forge.prestashop.com/browse/EMKTG-3410)
- [EMKTG-3411](https://forge.prestashop.com/browse/EMKTG-3411)

Fix : QA feedback

---

classes/ProductFilter/FilterApplication/AttributeQueryBuilder/BrandQueryBuilder.php
classes/ProductFilter/FilterApplication/AttributeQueryBuilder/CategoryQueryBuilder.php
classes/ProductFilter/FilterApplication/AttributeQueryBuilder/FeatureQueryBuilder.php
classes/ProductFilter/FilterApplication/AttributeQueryBuilder/OutOfStockQueryBuilder.php
classes/ProductFilter/FilterApplication/AttributeQueryBuilder/PriceQueryBuilder.php
classes/ProductFilter/FilterApplication/AttributeQueryBuilder/ProductIdQueryBuilder.php
classes/ProductFilter/FilterApplication/AttributeQueryBuilder/QueryBuilderInterface.php
classes/ProductFilter/FilterApplication/QueryBuilder.php

fix [EMKTG-3420](https://forge.prestashop.com/browse/EMKTG-3420)

fix: double same attribute handle

---

_dev/apps/ui/src/assets/scss/components/_gs-table-attribute-mapping.scss
_dev/apps/ui/src/components/product-feed/settings/shipping-setup/shipping-setup.vue
_dev/apps/ui/src/components/product-feed/settings/summary/summary.vue
_dev/packages/mktg-with-google-common/translations/en/ui.json

Related ticket => [EMKTG-3429](https://forge.prestashop.com/browse/EMKTG-3429)

fix: feedback qa review

---

_dev/apps/ui/src/components/product-feed/settings/product-selection/product-selection.vue
_dev/apps/ui/src/views/tunnel-product-feed.vue

related ticket => [EMKTG-3439](https://forge.prestashop.com/browse/EMKTG-3439)

Fix: synch not updated

---

_dev/apps/ui/.storybook/mock/product-feed.ts
_dev/apps/ui/src/assets/scss/layouts/_form.scss
_dev/apps/ui/src/assets/scss/pages/_product-selection.scss
_dev/apps/ui/src/components/commons/input-text-with-tag.vue
_dev/apps/ui/src/components/commons/multi-select-value.vue
_dev/apps/ui/src/components/product-feed/settings/product-selection/attributeMapCondition.ts
_dev/apps/ui/src/components/product-feed/settings/product-selection/filterValidator.ts
_dev/apps/ui/src/components/product-feed/settings/product-selection/line-filter.vue
_dev/apps/ui/src/components/product-feed/settings/product-selection/product-selection-localstorage.ts
_dev/apps/ui/src/components/product-feed/settings/product-selection/product-selection-utilities.ts
_dev/apps/ui/src/components/product-feed/settings/product-selection/product-selection.vue
_dev/apps/ui/src/components/product-feed/settings/product-selection/type.ts
_dev/apps/ui/src/components/product-feed/settings/summary/summary.vue
_dev/apps/ui/src/store/modules/app/actions.ts
_dev/apps/ui/stories/product-feed-settings.stories.ts
_dev/packages/mktg-with-google-common/translations/en/ui.json

Related ticket => [EMKTG-3391](https://forge.prestashop.com/browse/EMKTG-3391)

Feature : product filter errors

---

_dev/apps/ui/.cloud/deployment.tf

feat: artifact registry

---

_dev/apps/ui/src/assets/json/prestashopUrl.json

Related ticket => [SCE-658](https://forge.prestashop.com/browse/SCE-658)

[FEAT] update support link
