_dev/.storybook/mock/smart-shopping-campaigns.js, _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.spec.ts
We discovered when we don't have product approved by Google, we were able anyway to modify the filters.
The issue has been fixed in #829, but the related test wasn't added.
=> Add missing test for select filters button that should be disabled

_dev/.storybook/webpack.config.js
Build of storybook is currently broken because it does not recognize the typescript we recently integrated in one component. This PR adds ts-loader.
=> Fix build of storybook with Typescript in components

_dev/src/views/campaign-page.vue
Loading the SSC list takes too much time. This first PR is a quick win to remove a few seconds of loading time.
=> Do not wait for campaign filters to load before displaying ssc list

_dev/src/views/campaign-page.vue
6 seconds to complete
1.4 seconds to complete
=> Run all initial actions of campaign page in parallel when possible

_dev/src/store/modules/smart-shopping-campaigns/actions.ts
In case of problem retrieving filters, API sends 500 or 502
=> Check new error code in case of API problem

_dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-dimension.vue
Loader was not displaying because condition was not in array length
=> Fix: add loader displaying while waiting for dimensions in popin filters SSC

_dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-confirm-cancel.vue, _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin.vue
User chose dimension then chose filters then they save.
STEP 1 : It is now written next to the button 'dimension chosen + number of products affected'
User open back the popin to change filters, check another one, but do not save and click on back button : 
_Previous behaviour_  every checkbox was reset to empty
_Now_ user will go back to STEP 1 with their first selection
=> Fix : Change behaviour if user go back in filters

.github/workflows/cdn.yml, _dev/src/utils/Sentry.ts, _dev/src/views/debug.vue
We are currently relying on the PHP version to see on what version an error occured. But with the JS distributed via CDN, the JS version running on the browser is usually different from the module version.
We now set a version at build time, based on the release tag.
Example of debugging data:
=> Define app build version to ease debugging

_dev/.storybook/mock/google-ads.js, _dev/src/components/commons/popin-configured.vue, _dev/src/components/google-ads-account/google-ads-account-card.vue, _dev/src/views/onboarding-page.vue, _dev/stories/popin-configured.stories.ts
Transform popin in ps-modal, fix storybook and add vuejs dynamisation. 
The popin opens ONLY THE FIRST TIME WHEN google ads account is connected not on refresh of the page if the accounts is already onboarded
=> Implement popin to create first campaign once user is onboarded

_dev/.storybook/mock/product-feed.js, _dev/.storybook/mock/smart-shopping-campaigns.js, _dev/src/components/product-feed/settings/summary/summary.spec.ts, _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue, _dev/stories/product-feed-settings.stories.ts, _dev/stories/smart-shopping-campaign-creation.stories.ts
Add property "visible" to be on the same page as API data
Add loader props on stories
Add router params in product-feed-settings and mock it for the tests for the stories
Modify mock MSW to retrieve campaigns in stories smart shopping campaign edition 
Add `syncSchedule` in the right data in product feed stories
=> Fix storybook mock

_dev/src/components/commons/banner-campaigns.vue, _dev/src/components/commons/select-country.vue, _dev/src/components/google-ads-account/google-ads-account-popin-new.vue, _dev/src/components/product-feed/settings/target-countries/target-countries.vue, _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue, _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue, _dev/src/components/smart-shopping-campaigns/ssc-popin-activate-tracking.vue, _dev/src/views/campaign-page.vue, _dev/src/views/onboarding-page.vue, _dev/src/views/product-feed-page.vue
- Toast should not be displayed on empty state export status tab
- Target country selector : remove the icon cross (remove props isMultiple because the selector already save only one country)
- Creation campaign on banner; button should have same behaviour than the other create campaign (differenciate all ids and refs from modal to prevent them for opening twice)
- CSS : title spacing in popin module configured
=> Fix : CSS + unsolicited toast display + remarketing tag popin after click on banner

_dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table-row.vue
API needs to send ID in /ads-reporting/campaigns-performances but it's not doable at the moment
=> Campaign performances table : replace button because no link available yet

classes/Buffer/TemplateBuffer.php, classes/Handler/RemarketingHookHandler.php, classes/Provider/CartEventDataProvider.php, classes/Provider/ProductDataProvider.php
Save buffer of conversion action events in cache folder.
Fixes:
=> Fix an issue preventing the front office to be displayed in some cases when the module is enabled + Other improvements of conversion actions

classes/DTO/Remarketing/PurchaseEventData.php, classes/Provider/PurchaseEventDataProvider.php
Conversion value wasn't reported properly, as basic data was replaced by other details specified on https://support.google.com/google-ads/answer/9028614. They are now merged together (basic + specific), and the debugger now shows the actual cart total.
=> Add common data on conversion action about purchase to avoid conversion value = 1

_dev/src/utils/Sentry.ts
Remove a double `v` in the release tag.
=> Fix release reported on Sentry

_dev/src/views/product-feed-page.vue, _dev/stories/product-feed-page.stories.ts
The status was not loaded so the condition was always first false, then true which caused a small apparition then disparition of the toast
=> Fix toast bad displaying

_dev/src/store/modules/accounts/actions.ts
I recently saw my website was unverified again. It appears Google regurarly checks if the verification tag remains present.
On the documentation (https://support.google.com/merchants/answer/176793?hl=en#zippy=%2Cadd-an-html-tag), we can also read:
From now, the tag will only be removed when the GMC account is disconnected.
=> Keep the Google verification tag displayed after website is verified and claimed

_dev/src/assets/json/translations/de/ui.json, _dev/src/assets/json/translations/en/ui.json, _dev/src/assets/json/translations/es/ui.json, _dev/src/assets/json/translations/fr/ui.json, _dev/src/assets/json/translations/it/ui.json, _dev/src/assets/json/translations/nl/ui.json, _dev/src/assets/json/translations/pl/ui.json, _dev/src/assets/json/translations/pt/ui.json, _dev/src/assets/json/translations/ru/ui.json
At the moment, the landing page should display content about SSC, not PMax
=> Revert translations about PMax

_dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table-row.vue, _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list-row.vue
Currently the API does not return the campaign type on the reporting tab, and our interface displays "PMax" by default. This PR removes the label when the API does not give this information.
Screenshot from storybook:
=> Do not display Pmax when the campaign type is not known

_dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
The button was displayed after the loading of SSC and PMax campaigns, and could be missed by merchants as it may appeared after a few seconds.
This PR makes it disabled instead.
=> Show campaign type dropdown as disabled when there is only one type of campaign available

_dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table-row.vue
=> Fix the carriage return for campaigns without link in reporting tab

classes/Handler/RemarketingHookHandler.php
Conversion actions are reported to not work properly on some shops. My guess is another HTTP request flushes the events to send to Google because it is not properly set as ajax.
=> Add check about ajax requests

.github/workflows/cdn.yml, _dev/vue.config.js
At the moment, the app hosted on the CDN still tries to load the images stored on a shop (i.e `../modules/psxmarketingwithgoogle/views/img/pmax-modal-pmax-released-FR.png`). This means that for merchants who do not upgrade their module, some new images may be missing.
=> Use images use stored online instead of on the shop

_dev/.storybook/preview.js, _dev/src/components/campaign-creation/campaign-creation-filter-popin/campaign-creation-popin-recap.vue, _dev/src/components/campaign/campaign-table-list-row.vue, _dev/src/shims-tsx.d.ts, _dev/src/store/modules/campaigns/actions.ts, _dev/src/store/modules/product-feed/actions.ts, _dev/src/utils/Filters.ts
The way we display a price was different between the reporting and campaign list.
This PR updates the campaign tab, and makes sure a number is always displayed even if we don't provide properly the currency code.
It appeared whatever the language we set in the back office, the way prices are displayed never changed.
This was caused by the use of a variable that did not exist.
=> Fix display of currency on campaign list + fix language context when formating a price

_dev/src/assets/json/translations/en/ui.json, _dev/src/components/campaign-creation/campaign-creation.spec.ts, _dev/src/components/campaign-creation/campaign-creation.vue, _dev/tests/init.ts
* Update minimal value of campaigns end date so the merchant cannot select a day before today's date or the campaign start date
* Changes the buttons in the end date datepicker: We had issues where removing the date only closed the calendar, but resetting the date actually removed the date. This PR updates the buttons to only keep the one that removes the date.
* Show the end date in a different state when it is before today's date.
=> Forbid setting campaigns end date before today

_dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue, _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue, _dev/src/utils/LocalStorage.ts, _dev/stories/product-feed-settings.stories.ts
Based on https://github.com/PrestaShopCorp/psxmarketingwithgoogle/pull/1084, display countries in target countries options only if they have a carrier that delivers to it.
=> Display countries while importing shipping settings only if they have one associated carrier

_dev/.storybook/mock/ps-accounts.ts, _dev/.storybook/preview-head.html, _dev/.storybook/preview.js, _dev/src/views/onboarding-page.vue, _dev/stories/general-errors.stories.ts, _dev/stories/onboarding-page.stories.ts, _dev/stories/ps-account-card.stories.ts
PS Accounts now loads its context exclusively from `window`. We had to update our stories to make it work on Storybook.
=> Fix PS Accounts on Storybook

_dev/.storybook/mock/product-feed.ts, _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue, _dev/stories/product-feed-settings.stories.ts
Reviewing the diff should be easier by ignoring white spaces.
This PR updates the stories about the step 2 of the product feed:
* Import method: the countries do not disappear anymore after loading
* Estimate method: Add mocked details to have a complete form displayed
=> Update stories about Delivery rates

.github/workflows/publish.yml
=> Add prefix URL to sourcemaps sent to Sentry so they can be used on stacktraces

_dev/src/components/commons/glass.vue, _dev/src/components/google-account/google-account-card.vue
Improve the management of our popup to onboard Google accounts.
Related issue: https://sentry.io/organizations/prestashop/issues/3772609582/?project=5984715&query=is%3Aunresolved&referrer=issue-stream
* Fixes issues preventing the focus and the close to work from the glass (grey transparent screen in background).
* Fixes bad implementation of event listeners
* Fixes the triggering of issues related to CORS policy when possible (We are not allowed to interact with the popul while it displays a page from google.com)
=> Avoid issues related to CORS policy on popup

_dev/apps/verification-tag/src/index.ts, _dev/apps/verification-tag/src/verification-tag-retriever.spec.ts, _dev/apps/verification-tag/src/verification-tag-retriever.ts, psxmarketingwithgoogle.php
- Do not trigger the process when we can't retrieve the shop ID or token from PS Accounts
- (Re)Claim the website after a successful verification.
- Limit the events sent to Sentry (Half of them are sent)
- Send more details to Sentry to ease debug (response content, correlation ID)
=> Improve verification tag renewal process from feedback

_dev/apps/ui/.storybook/mock/product-feed.ts, _dev/apps/ui/src/assets/json/googleUrl.json, _dev/apps/ui/src/assets/json/translations/en/ui.json, _dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details-row.spec.ts, _dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details-row.vue, _dev/apps/ui/src/store/modules/product-feed/state.ts, _dev/apps/ui/stories/product-feed-table-status-details.stories.ts
* Switch component _dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details-row.vue on TypeScript
* Add related types
* Add a default message recommending to the merchant to check its account errors, with a direct link
=> Display disapproved products even without issues linked to them

.github/workflows/php.yml, classes/Database/Uninstaller.php, classes/Provider/CarrierDataProvider.php, classes/Repository/CarrierRepository.php, classes/Repository/ModuleRepository.php, classes/Repository/StateRepository.php, composer.json, composer.lock, config/admin/installer.yml, config/admin/provider.yml, config/common/repository.yml, controllers/admin/AdminPsxMktgWithGoogleModuleController.php, psxmarketingwithgoogle.php
Since the first implementation of PHPStan in our development process, we did not increase the version because the docker image had changed. We were stuck on `PHPStan - PHP Static Analysis Tool 0.12.89`, a version released on 09/06/2021.
Keeping our tools up-to-date is important for the stability of our projects. However newer versions were using PHP 8 in their Docker image, preventing it to work with old version of PrestaShop.
This PR add PHPStan as a composer dependency so we can control the version used with the lock file, and we updated the CI workflow so PrestaShop versions are manually downloaded and unzipped.
=> Use latest version of PHPStan

_dev/apps/ui/src/store/modules/google-ads/actions.ts
This makes the Remarketing tags card hidden after a disconnection from Google Ads
=> Reset campaigns lists when Google Ads is disconnected

_dev/apps/ui/src/components/campaigns/campaign-card.vue, _dev/apps/ui/src/components/commons/popin-configured.vue, _dev/apps/ui/src/views/onboarding-page.vue
The conditions to open the remarketing tag popin must be the same between the "Configuration successful popin" and the Google Ads account card.
=> Open remarketing tag popin when after closing the config success popin

_dev/apps/ui/src/main.ts
We now fallback on an encoded string from the current domain
=> Keep control on shop ID when PS Account does not provide it

_dev/apps/verification-tag/src/verification-tag-retriever.ts
HTTP 400 is tolerated on `claim` if Google requests overwrite to be set as true.
The proper message will be displayed on the configuration page.
=> Ignore response of claim call when overwrite is needed during reverification

_dev/apps/ui/src/App.vue
Since we load PS Accounts components from an external resource, it seems the mounted() event is triggered later, even too late compared to subcomponents already triggering API calls.
This PR moved the API initialization earlier in the process, so all API calls can succeed
=> Init API clients on App creation, not mount

_dev/apps/ui/src/assets/scss/base/_common.scss, _dev/apps/ui/src/assets/scss/components/_sync-history.scss, _dev/apps/ui/src/assets/scss/components/_table-carriers.scss, _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue, _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-card.spec.ts, _dev/apps/ui/src/components/product-feed-page/submitted-products/products-status-card.vue, _dev/apps/ui/src/components/product-feed-page/submitted-products/submitted-products.vue
* [Remove seconday color on some texts, as the grey was now too bright](https://github.com/PrestaShopCorp/psxmarketingwithgoogle/pull/1450/commits/d0f29670146d5358e5b1a8eee82cf6ef4534945e)
* [Make more links displayed in blue even when muted](https://github.com/PrestaShopCorp/psxmarketingwithgoogle/pull/1450/commits/0972b11567624ed5193433da729978ab780ae4f4)
=> Rebranding fixes part 2

.github/workflows/cdn-preproduction.yml, .github/workflows/cdn.yml, .github/workflows/publish.yml
Replace depreciated commands as per : https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> replace depreciated command

_dev/packages/mktg-with-google-common/translations/en/ui.json
For the first iteration of the product feed rework, we finally keep the existing sync summary on the left.
=> Bring back translations about sync summary

_dev/apps/ui/src/components/merchant-center-account/merchant-center-account-alert-suspended.vue, _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-card.vue, _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-links.ts, _dev/apps/ui/src/components/product-feed-page/sync-overview.vue, _dev/apps/ui/src/store/modules/accounts/state.ts, _dev/apps/ui/stories/product-feed-page.stories.ts
=> Display account suspension alert on new product feed page

_dev/apps/ui/.storybook/mock/product-feed.ts, _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.spec.ts, _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
This PR implements an example of display for currencies inside the product feed's configuration.
It shows how we could display an additional case where a specific currency was not found on the shop.
=> Display currencies in product feed's configuration

_dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.spec.ts, _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue, _dev/apps/ui/stories/product-feed-page/dashboard/product-feed-page-components-configuration.stories.ts
In this story, the alert used to be a warning (= yellow), which is wrong
=> Fix color of alert when an unrelated currency is sent by the API

_dev/apps/ui/src/bc-ante-vite.ts
The use of `import.meta.url` is unavailable in scripts not imported as module.
This is precisely how the merchants are loading the file app.js in previous versions.
We had to find another solution for them in order to load dynamically the new script.
=> Fix backward compatibility

_dev/apps/ui/src/components/campaign/reporting/key-metrics/key-metrics-chart-wrapper.vue
On betas 1 & 2, reducing then increasing the width of the page has a bad result on the reporting graph, as it was not reacting to the width increase and stayed small on the page.
=> Fix responsiveness of graph

_dev/packages/mktg-with-google-common/translations/en/ui.json
> **CA 15 :**
**Given that :** a merchant that hasn't created his first campaign and he visits the campaign page
**When :** he click on the CTA 'Create your first PMax campaign' displayed in a banner at the top of the page
**Then :** he is redirected on the campaign creation form
=> Follow acceptance criteria for the first campaign creation CTA

_dev/apps/ui/src/App.vue, _dev/apps/ui/src/components/enhanced-conversions/notification-panel.vue, _dev/apps/ui/src/store/modules/google-ads/actions.ts
- Fix an unrelated value happening while disconnecting Google Ads
- Plug the notification system to the app
- Avoid refreshing the Google Ads account when no account is onboarded in the first place
=> Fine tune Enhanced conversion

_dev/apps/ui/src/assets/scss/components/_badge.scss, _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue, _dev/apps/ui/src/components/product-feed-page/dashboard/status-card.vue, _dev/apps/ui/src/components/product-feed-page/non-compliant-products-details-page/non-compliant-products-details-row.vue, _dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-row.vue
* font-size: 13px
* font-weight: 600
Source: https://www.figma.com/file/BhjRbRHDyte9F0HKTP2yUW/Product-Feed?type=design&node-id=617-10681&mode=design&t=h9377QZgna3PytG8-4
--------
* font-size: 16px
* font-weight: 500
Source: https://www.figma.com/file/BhjRbRHDyte9F0HKTP2yUW/Product-Feed?type=design&node-id=20-7007&mode=design&t=h9377QZgna3PytG8-4
--------
* font-size: 13px
* font-weight: 500
Source: https://www.figma.com/file/BhjRbRHDyte9F0HKTP2yUW/Product-Feed?type=design&node-id=19-11377&mode=design&t=h9377QZgna3PytG8-4
=> Update font sizes of product feed pages

_dev/apps/ui/src/store/modules/product-feed/actions.ts
PsEssentials URLs are deprecated. It should have worked until then tho, but it's getting 
hard to diagnose why the CORS is not going up well in the PsxMarketingWithGoogle context, while:
```
❯ curl -s -I "https://eventbus-sync.psessentials.net/sync/trigger-full" | grep origin  
access-control-allow-origin: *
```
* https://forge.prestashop.com/browse/EB-1304
* https://docs.cloudsync.prestashop.com/api-doc/sync-api#/operations/AuthSyncController_triggerSyncAuth
=> Fix CloudSync sync-api URL

_dev/apps/ui/src/assets/scss/components/_google-issues.scss
=> Display links as blocks

_dev/apps/ui/src/store/modules/product-feed/actions.ts
This avoids loading the whole list on the API side
=> Set a limit when loading disapproved products

_dev/apps/ui/.storybook/mock/merchant-center-account.ts, _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-card.vue, _dev/apps/ui/stories/merchant-center-account-card.stories.ts
This PR fixes the display of the status badge when the account is not yet verified and claimed
=> Update condition to display GMC badge

_dev/apps/ui/src/lib/i18n.ts
Fixes the error `gT[e] is not a function` when the translation file of the current language does not exist.
=> Fix error on app startup while loading an unsupported language

_dev/apps/ui/src/store/modules/campaigns/actions.ts
`POST conversion-actions/enhanced` returns empty responses. Trying to get the json contents will always fail.
=> Do not try to get json contents from en empty response

.github/workflows/php.yml, _dev/apps/verification-tag/src/verification-tag-retriever.spec.ts, _dev/apps/verification-tag/src/verification-tag-retriever.ts
**Do not send 403 errors to Sentry in verification tag retrieval**
**Update verification tag retrieval tests to enhance error handling**
- Modified the "handles 403 Forbidden error gracefully" test to throw an HttpClientError with a 403 status code.
- Updated the "handles 404 Not Found error" test to throw an HttpClientError with a 404 status code.
- Adjusted the "stops when token retrieval fails" test to throw an HttpClientError with a 500 status code and added an assertion to ensure Sentry.captureException is called.
**Update PHP-CS-Fixer action in GitHub workflow**
- Changed the PHP-CS-Fixer command from a direct run to using the PrestaShop GitHub Action for PHP-CS-Fixer.
=> chore: Update verification tag retrieval tests to enhance error handling

_dev/apps/verification-tag/README.md, _dev/apps/warning-messages/README.md
- Added verification tag README.md
- Added warning messages README.md
=> chore: add README.md
